version: 0.0
os: linux

files:
  - source: dist/
    destination: /var/www/test-angular-project/dist
    overwrite: true

permissions:
  - object: /var/www/test-angular-project
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory

  - object: /var/www/test-angular-project
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 644
    type:
      - file

hooks:
  ApplicationStart:
    - location: scripts/application-start-hook.sh
      timeout: 300
      runas: ec2-user
