version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo Build start
      - npm install
      - npm run build

artifacts:
  base-directory: dist
  files:
    - '**/*'
    - appspec.yml
    - 'scripts/**/*'
